// <auto-generated />
namespace Bee_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateappointmentmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateappointmentmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201805052223245_update appointment model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
